[files]
extend-exclude = [
    ".git",
    "target",
    "corpus/conformance",
]

[default.extend-words]
APPn = "APPn"
flate = "flate"
iy = "iy"
ois = "ois"
Pn = "Pn"
Psot = "Psot"
setp = "setp"
SIZ = "SIZ"
Siz = "Siz"
TPsot = "TPsot"
YTO = "YTO"
siz = "siz"
yto = "yto"
